"""Changed column name from old_name to new_name

Revision ID: 13c8829cfafd
Revises: 3337024ff65e
Create Date: 2025-04-06 16:19:50.417376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13c8829cfafd'
down_revision = '3337024ff65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Booking_Accept_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('service_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('Booking_Accept_date')

    # ### end Alembic commands ###
