"""Your message here

Revision ID: 72674e04062e
Revises: 33bc329f51db
Create Date: 2025-04-08 17:06:29.615859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72674e04062e'
down_revision = '33bc329f51db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_completed_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('order_completed_date')

    # ### end Alembic commands ###
