"""Your message here

Revision ID: b9151e54c5b0
Revises: 72674e04062e
Create Date: 2025-04-08 21:13:53.845776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9151e54c5b0'
down_revision = '72674e04062e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='payment_booking_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='payment_pkey'),
    sa.UniqueConstraint('booking_id', name='payment_booking_id_key')
    )
    # ### end Alembic commands ###
