"""Added booking_id and unique constraint to reviews

Revision ID: e52d8aa7910e
Revises: 19007fa49fcc
Create Date: 2025-04-07 19:53:06.656373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52d8aa7910e'
down_revision = '19007fa49fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('_user_booking_uc', ['user_id', 'booking_id'])
        batch_op.create_foreign_key(None, 'booking', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('_user_booking_uc', type_='unique')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
